### PR TITLE
enforce only 1 inlet to N outlets ,fixes #21

### LINKED ISSUE #21: GUI: odd inlet connection handling
if you attempt to connect an outlet from object B to an inlet of object C , were inlet of object C is already connected. it will not connect correctly  
expected behaviour: delete the existing connection to object C inlet, and connect object B.
(this is how it works for Reaktor, and others) 

consider the following:
A -> C
you wish to connect to 
A->B->C
so you create B, and then connect A to B, then B to C... we don't want to have to first disconnect A-C its should be implicit. (makes refactoring patches much quicker)

### PR DESCRIPTION
**Pull request by TheTechnobear**

### CODE REVIEW

**Comment by JohannesTaelman** [comment]
Problem now is that connections get lost when mutating an object, or when
objects auto-mutate  to a homonym, they were preserved before.

In terms of UX, I think it is more important to change the cursor suring
drag and drop:
* unplugging by dropping on the patch canvas
* dropping on an in- or outlet that would result in an invalid net

**Comment by JohannesTaelman** [comment]
So I reverted this one, sorry, breaks too much.

**Comment by TheTechnobear** [comment]
What is a homonym (in this context) , and an example of mutation that
fails.

I really fear we are pandering to 'technical cases' rather than what the
majority of users will do ... this would be a big mistake.
Do you want 1000 users who use axoloti day to day or 50 experts? ... We can
do both but we need to ensure the average user is catered for first. (
imho)

**Comment by JohannesTaelman** [comment]
homonyms = multiple objects sharing the same name. Like "mix/mix 2" exists for audio and control rate datatypes. A bit comparable to function/method overloading.
An example of something that broke: create a "mix 2" of the audio type, connect a control rate outlet to one of its inlets and it promotes to a "mix 2" of control rate type. But with your commit, it does not preserve the connections anymore.

Sure, I want 1000 happy users!

**Comment by TheTechnobear** [comment]
ok, then I think we need to look at why the changes break this... fundamentally there is no reason why it should.... it dealt with inlets and outlets, not types of inlets and outlets... so perhaps a more 'fundamental' problem.

**Pull request merged**
